### PR TITLE
Merge 'develop' onto master as initial release

### PR DESCRIPTION
**Pull request by RichardMills**
I think we should merge "develop" up to master so there's a primary area. Alternately, we could set 'develop' as the default branch. We should still have something on master.

### CODE REVIEW

**Comment by OtherDevOpsGene** [comment]
I set the default branch to develop

**Comment by RichardMills** [comment]
Previously? I got master earlier when I checked out earlier.

**Comment by OtherDevOpsGene** [comment]
This morning, after you asked.

**Comment by RichardMills** [comment]
this is forever old. Closing to get rid of it. Re-open if we actually want it.

**Pull request closed without merging**
